modLoader="javafml" #mandatory
loaderVersion="[46,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/Alex-the-666/AlexsMobs/issues" #optional
[[mods]] #mandatory
modId="alexsmobs" #mandatory
version="1.22.6-downvote20231114" #mandatory
displayName="Alex's Mobs Downvote Edition" #mandatory
displayURL="https://github.com/Ironnoob73/AlexsMobs" #optional
authors="Original: Alexthe668, Carro1001, Paint_Ninja, §7Modified by: LD_Anvil" #optional
description='''§c§l强力削弱修改版，建议用于替换整合包中的模组而非独自使用。'''
[[dependencies.alexsmobs]] #optional
    # the modid of the dependency
    modId="citadel" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[2.4.4,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="AFTER"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[modproperties.alexsmobs]
    catalogueItemIcon="alexsmobs:bear_dust"
[[dependencies.alexsmobs]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.65,)"
    ordering="NONE"
    side="BOTH"